import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { Questionnaire, PdfExportOptions } from '../types';

export class PdfExporter {
  /**
   * Export questionnaire responses to PDF
   */
  static async exportToPdf(
    questionnaire: Questionnaire,
    responses: Record<string, any>,
    options: PdfExportOptions = {}
  ): Promise<void> {
    const {
      filename = `${questionnaire.title}-${new Date().toISOString().split('T')[0]}.pdf`,
      title = questionnaire.title,
      interviewerName = 'Interviewer',
      candidateName = 'Candidate',
      date = new Date(),
    } = options;

    // Create a temporary container to render
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.width = '210mm';
    container.style.padding = '20px';
    container.style.backgroundColor = 'white';
    container.style.fontFamily = 'Arial, sans-serif';
    container.style.fontSize = '12px';

    // Build HTML content with better styling
    let html = `
      <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #1a3a52; margin: 0 0 5px 0; font-size: 24px;">${title}</h1>
          <div style="height: 2px; background: linear-gradient(to right, #3b82f6, #10b981); margin: 15px 0;"></div>
        </div>
        
        <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="width: 33%; padding: 8px;"><strong>Date:</strong><br/>${date.toLocaleDateString()}</td>
              <td style="width: 33%; padding: 8px;"><strong>Interviewer:</strong><br/>${interviewerName}</td>
              <td style="width: 33%; padding: 8px;"><strong>Candidate:</strong><br/>${candidateName}</td>
            </tr>
          </table>
        </div>
    `;

    if (questionnaire.description) {
      html += `<p style="color: #666; margin-bottom: 20px; font-style: italic; border-left: 4px solid #3b82f6; padding-left: 15px;">${questionnaire.description}</p>`;
    }

    html += '<div style="margin-top: 25px;">';

    // Add form fields with better styling
    for (const field of questionnaire.fields) {
      const value = responses[field.id] || '---';
      const displayValue = Array.isArray(value) ? value.join(', ') : String(value);

      html += `
        <div style="margin-bottom: 15px; page-break-inside: avoid;">
          <label style="display: block; font-weight: bold; color: #1a3a52; margin-bottom: 5px;">
            ${field.label}${field.required ? '<span style="color: red;"> *</span>' : ''}
          </label>
          <div style="background-color: #f5f5f5; padding: 10px; border-left: 3px solid #3b82f6; min-height: 20px;">
            ${displayValue}
          </div>
        </div>
      `;
    }

    html += `
        </div>
        <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #ccc; font-size: 11px; color: #999;">
          <p>Generated by Interview Data Collector PWA</p>
          <p>Generated on ${new Date().toLocaleString()}</p>
        </div>
      </div>
    `;

    container.innerHTML = html;
    document.body.appendChild(container);

    try {
      // Convert HTML to canvas
      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
      });

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [210, 297],
      });

      const imgData = canvas.toDataURL('image/png');
      const pageCount = Math.ceil(canvas.height / 841); // A4 height in pixels at 96dpi

      for (let i = 0; i < pageCount; i++) {
        if (i > 0) {
          pdf.addPage();
        }

        const y = -(i * 841);
        pdf.addImage(imgData, 'PNG', 0, y, 210, canvas.height / pageCount);
      }

      // Download PDF
      pdf.save(filename);
    } finally {
      document.body.removeChild(container);
    }
  }

  /**
   * Export multiple responses to a single PDF
   */
  static async exportMultipleToPdf(
    questionnaire: Questionnaire,
    responsesList: Array<{ responses: Record<string, any>; candidateName: string }>,
    filename: string = `${questionnaire.title}-batch-${new Date().toISOString().split('T')[0]}.pdf`
  ): Promise<void> {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    for (let i = 0; i < responsesList.length; i++) {
      if (i > 0) {
        pdf.addPage();
      }

      const response = responsesList[i];

      // Create temporary content for each response
      const container = document.createElement('div');
      container.style.position = 'absolute';
      container.style.left = '-9999px';

      let pageHtml = `
        <div style="font-family: Arial, sans-serif;">
          <h1>${questionnaire.title}</h1>
          <p><strong>Candidate:</strong> ${response.candidateName}</p>
      `;

      for (const field of questionnaire.fields) {
        const value = response.responses[field.id] || '---';
        pageHtml += `
          <p>
            <strong>${field.label}:</strong> ${value}
          </p>
        `;
      }

      pageHtml += '</div>';
      container.innerHTML = pageHtml;
      document.body.appendChild(container);

      try {
        const canvas = await html2canvas(container);
        const imgData = canvas.toDataURL('image/png');
        pdf.addImage(imgData, 'PNG', 10, 10, 190, i === 0 ? 277 : 267);
      } finally {
        document.body.removeChild(container);
      }
    }

    pdf.save(filename);
  }
}
